repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        entry: black
        language_version: python
        types: [python]
        args: [--line-length=88]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        entry: mypy
        language_version: python
        types: [python]
        additional_dependencies:
        - pydantic-settings
        - pydantic
        - requests
        - types-requests
        args: [--ignore-missing-imports]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        entry: ruff check
        language_version: python
        types: [python]
        args: [--fix]
